### ISSUE TITLE
(hypothetical) the robot drives backwards

### ISSUE THREAD

**Issue by ghost** [FRC-Team-3140/FRC2015Code#1]
push forward, it goes back yes it does

**Comment by rogerisprettybad** [comment]
Roger is pretty bad.

**Comment by afrozaky** [comment]
drivayy lmao

**Comment by rgmonteray** [comment]
i love band.

**Comment by rogerisprettybad** [comment]
If you push forward and it goes back use some duck tape

**Comment by rgmonteray** [comment]
i love band. band loves you.

**Comment by rogerisprettybad** [comment]
Zaky is immature

**Comment by rogerisprettybad** [comment]
<--------That's Josh

**Comment by afrozaky** [comment]
"Zaky is immature"
ayy lmao

**Comment by dennisisprettybad** [comment]
<----- No, this is Josh's spirit animal.

**Comment by nhobs1999** [comment]
rache we all love band

**Comment by rgmonteray** [comment]
true life.

**Comment by rogerisprettybad** [comment]
motorsWrite()

Description

Controls the speed and direction of the two motors connected to the robot's wheels. motorsWrite() needs values between -255 and 255. If the value is greater than 0, the wheel turns forward. If less than 0, the motor turns backwards.

**Comment by punishedchadknausfan** [comment]
We are done learning hypothetically
