### ISSUE TITLE
Commit 3a1e4e4 changes

### ISSUE THREAD

**Issue by player1537** [FRC-Team-3140/FRC2015Code#5]
Specifically, I'm looking through [this diff](https://github.com/FRC-Team-3140/FRC2015Code/commit/3a1e4e41b415b916c7665d972299a2314435b1aa).

In `OI.java`, the constructor should not take any arguments. For determining whether tank drive or arcade drive is active, instead of passing a boolean to the constructor, have it try to instantiate as many joysticks as it can, and store them in an array, with a particular convention (e.g. `joysticks[0]` is left, etc). 

I also would like to see `joystickTolerance()` take 2 arguments, `rawJoystickValue` and `joystickDeadzone`. And then make a 1 argument version which calls `joystickTolerance(rawJoystickValue, defaultJoystickDeadzone)` that way there is a possibility of changing the deadzones more easily than doing something hacky.

In `_getRightDriveAxis()`, the intention of the underscore functions was to return the raw axis values. So, having the `if (tankDrive)` part is fine, since it's still returning the raw values for each type of joystick. It's the `joystickTolerance()` part that should be moved to the regular `getRightDriveAxis()` function. Andy suggested renaming the underscore functions to something like `private double getRawRightDriveAxis()`, which would be a good idea to help remember the purpose of each.

`CommandBase.java` looks correct.

`TankDrive.java` should probably have the `update()` function removed, unless it is actually getting used, but I haven't seen any reference in the documentation. The body of `initialize()` looks wrong, and should probably just be set to 0 for each. In `setSpeeds()`, you should build on the `setLeftSpeed()` and `setRightSpeed()` functions already written. Otherwise, the left/right ones should build on `setSpeeds()` by keeping track of the last speed written to the right side (if in `setLeftSpeed()`) and passing that to `setSpeeds()`.

In `driveTrain.java`, you should rename it to `DriveTrain.java` to match Java conventions. The `setPower()` function should build on `setLeftPower()` and `setRightPower()`.

---

One last thing: I told Josh to come in and remind you all this every hour or so, but please push lots of code to the repo. The awesome features of Git aren't used if you only push once a day. Ideally, once you have most of the code refactored, you should be committing for every major and minor change you make. For example, changing a tolerance value based on physical testing, or adding a new command. For now, you should definitely be commiting/pushing every hour (or even better, every 30 minutes).

Don't worry if the code isn't perfect when you commit/push. It's just to help us stay in the loop and see how things change over time and what we can do to help.

**Comment by dennisisprettybad** [comment]
Cool Beans
