### ISSUE TITLE
GrabberArm and WinchLifter

### ISSUE THREAD

**Issue by player1537** [FRC-Team-3140/FRC2015Code#6]
Don't forget to do `setDefaultCommand(new Grabber())` for the `GrabberArm`, and similarly for the `WinchLifter`. You do this in the `initDefaultCommand()` methods of those subsystems.

**Comment by player1537** [comment]
Whoops, assigning people is hard.

**Comment by RccCookie** [comment]
Added both default commands to both subsystems, thanks for pointing this out.
