### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by RccCookie** [FRC-Team-3140/FRC2015Code#7]
Hey guys, testing out the code on the robot and it is returning some errors:

ERROR Unhandled exception: edu.wpi.first.wpilibj.command.IllegalUseOfCommandException: A default command must require the subsystem at [edu.wpi.first.wpilibj.command.Subsystem.setDefaultCommand(Subsystem.java:96), org.usfirst.frc0.MyRobot.subsystems.DriveTrain.initDefaultCommand(DriveTrain.java:30), edu.wpi.first.wpilibj.command.Subsystem.getDefaultCommand(Subsystem.java:117), edu.wpi.first.wpilibj.command.Scheduler.run(Scheduler.java:232), org.usfirst.frc0.MyRobot.Robot.disabledPeriodic(Robot.java:80), edu.wpi.first.wpilibj.IterativeRobot.startCompetition(IterativeRobot.java:102), edu.wpi.first.wpilibj.RobotBase.main(RobotBase.java:234)]

Any of you guys know what I am doing wrong for these errors, I realize most of them revolve around calling the commands, such as default command, but I am lost on how to fix these issues. Whenever you guys get the time to look and see the fixes that are needed.

**Comment by player1537** [comment]
In [`TankDrive.java`](https://github.com/FRC-Team-3140/FRC2015Code/blob/master/MyRobot/src/org/usfirst/frc0/MyRobot/commands/TankDrive.java#L29-L31), you should be doing `requires(driveTrain)` instead, from where you define it in [`CommandBase.java`](https://github.com/FRC-Team-3140/FRC2015Code/blob/master/MyRobot/src/org/usfirst/frc0/MyRobot/commands/CommandBase.java#L25).

Then in [`DriveTrain.java`](https://github.com/FRC-Team-3140/FRC2015Code/blob/master/MyRobot/src/org/usfirst/frc0/MyRobot/subsystems/DriveTrain.java#L28-L32) you should be doing `setDefaultCommand(new TankDrive())`.

In [`Robot.java`](https://github.com/FRC-Team-3140/FRC2015Code/blob/master/MyRobot/src/org/usfirst/frc0/MyRobot/Robot.java), you probably should try creating a brand new Command-Based Robot (without using RobotBuilder) and see what code they have there. I have a feeling that [`robotInit()`](https://github.com/FRC-Team-3140/FRC2015Code/blob/master/MyRobot/src/org/usfirst/frc0/MyRobot/Robot.java#L48-L67) is not correct, and could be causing problems. Similarly, remove [these lines](https://github.com/FRC-Team-3140/FRC2015Code/blob/master/MyRobot/src/org/usfirst/frc0/MyRobot/Robot.java#L33-L40) in `Robot.java`, as I'm almost certain they don't belong there.

Let me know if those fix it for you.

**Comment by RccCookie** [comment]
Most of it worked, and yes it was robotInit() causing the problems. But, a new problem has arisen, the robot can only turn right through the Z axis going positive on a joystick...so that is something that needs to be worked on.

**Comment by rogerisprettybad** [comment]
int joy_x;
  int joy_y;
  int joy_threshold = 10;

  while(true)
  {
    joy_x = vexRT[Ch1];
    joy_y = vexRT[Ch3];

/_+++++++++++++++++++ Drive Code +++++++++++++++++++_/

```
// Forward
if((abs(joy_y) > joy_threshold) && (joy_y > 0))
{
  motor[leftDrive]  = (joy_y);
  motor[rightDrive] = (joy_y);
}

// Backwards
else if((abs(joy_y) > joy_threshold) && (joy_y < 0))
{
  motor[leftDrive]  = (joy_y);
  motor[rightDrive] = (joy_y);
}

//Right Movement and Spin
else if((abs(joy_x) > joy_threshold) && (joy_x > 0))
{
  motor[backDriveL] = (joy_x);
  motor[backDriveR] = (joy_x);
  motor[leftDrive] = (joy_x);
  motor[rightDrive] = -1*(joy_x);
}

//Left Movement and Spin
else if((abs(joy_x) > joy_threshold) && (joy_x < 0))
{
  motor[backDriveL] = (joy_x);
  motor[backDriveR] = (joy_x);
  motor[leftDrive] = -1*(joy_x);
  motor[rightDrive] = (joy_x);
}

//Else - Stop Motors
else
{
  motor[leftDrive] = 0;
  motor[rightDrive] = 0;
  motor[backDriveL] = 0;
  motor[backDriveR] = 0;
}
```

**Comment by player1537** [comment]
Here's one problem: [`TankDrive.java` has right and left mixed up in `execute()`](https://github.com/FRC-Team-3140/FRC2015Code/blob/e7bc64f07db344e3476505d55eba41ed9ccbca50/MyRobot/src/org/usfirst/frc0/MyRobot/commands/TankDrive.java#L72-L74).

Otherwise, the rest of the code seems okay. `OI.java` has a couple of oddities, but nothing that looks outright wrong. 

When you say "Z Axis", do you mean twisting the joystick, or pushing it forward/backwards, or left/right? Z Axis would normally mean twisting. 

rogerisprettybad, what is that code from?

Also, who is rogerisprettybad?

**Comment by ghost** [comment]
Yes the Z_axis is twisting. We'll look into OI.java, but our priority is getting tank drive down.
Also, rogerisprettybad is Dennis.

**Comment by player1537** [comment]
On [this line](https://github.com/FRC-Team-3140/FRC2015Code/blob/e7bc64f07db344e3476505d55eba41ed9ccbca50/MyRobot/src/org/usfirst/frc0/MyRobot/OI.java#L89) and [this one](https://github.com/FRC-Team-3140/FRC2015Code/blob/e7bc64f07db344e3476505d55eba41ed9ccbca50/MyRobot/src/org/usfirst/frc0/MyRobot/OI.java#L109), try changing which axis you get. Online it seems to say that axis 2 is the forward/backward one, but maybe something's weird with our joysticks. Also check if [this code](https://github.com/FRC-Team-3140/FRC2015Code/blob/e7bc64f07db344e3476505d55eba41ed9ccbca50/MyRobot/src/org/usfirst/frc0/MyRobot/OI.java#L70-L74) is working correctly (try printing out `joystick[0]` and `joystick[1]`, they should be non-null). 

Also, [this logic is wrong](https://github.com/FRC-Team-3140/FRC2015Code/blob/e7bc64f07db344e3476505d55eba41ed9ccbca50/MyRobot/src/org/usfirst/frc0/MyRobot/OI.java#L79).

**Comment by punishedchadknausfan** [comment]
Resolved by [the first commit made on Jan 20](https://github.com/FRC-Team-3140/FRC2015Code/commit/9a778fb5c10a6456c5896e4fa9239b2bcad0d6ba)
